<!DOCTYPE html>
<html>
    <link href="css/style.css" rel="stylesheet" />
    <body style="background: <?= $this->kleur(); ?>">
        <div id="container">
            <header>
                <h1><?= $this->translate('text.header');?></h1>
            </header>
            <p><?= $this->loginFormulier(); ?></p>
            <nav>
                <ul>
                    <!--<li><a href="">Home</a></li>
                    <li><a href="">Test</a></li>-->
                    <?= $this->navigation()->menu(); ?>
                </ul>
            </nav>
            <section>
                <article>
                    <?= $this->layout()->content; ?> 
                    <aside>
                        <h2>Social media</h2>
                    </aside>
                </article>
            </section>
        </div>
    </body>
</html>
