<!DOCTYPE html>
<html>
    <link href="css/style.css" rel="stylesheet" />
    <body>
        <div id="container">
            <header>
                <h1>Project1-final</h1>
            </header>
            <nav>
                <ul>
                    <li><a href="">Home</a></li>
                    <li><a href="">Test</a></li>
                </ul>
            </nav>
            <section>
                <article>
                    <?php echo $this->layout()->content; ?> 
                    <aside>
                        <h2>Social media</h2>
                    </aside>
                </article>
            </section>
        </div>
    </body>
</html>
